import { Card } from '../../../types';

// Alphabet (including diacritics: ă, â, î, ș, ț)
export const alphabet: Card[] = [
  [
    { text: 'Румынский алфавит' },
    { text: '26 букв + 5 диакритик' },
    { text: 'ă â î ș ț', fontSize: 20 },
  ],
  [
    { text: 'а' },
    { text: 'a' },
    { text: 'A a', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'э' },
    { text: 'ə' },
    { text: 'Ă ă', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'ы' },
    { text: 'ɨ' },
    { text: 'Â â', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'б' },
    { text: 'b' },
    { text: 'B b', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'перед a,o,u = к' },
    { text: 'k' },
    { text: 'перед e,i = ч' },
    { text: 't͡ʃ' },
    { text: 'C c', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'д' },
    { text: 'd' },
    { text: 'D d', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'э' },
    { text: 'e' },
    { text: 'E e', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'ф' },
    { text: 'f' },
    { text: 'F f', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'перед a,o,u = г' },
    { text: 'ɡ' },
    { text: 'перед e,i = дж' },
    { text: 'd͡ʒ' },
    { text: 'G g', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'х' },
    { text: 'h' },
    { text: 'H h', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'и' },
    { text: 'i' },
    { text: 'I i', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'ы' },
    { text: 'ɨ' },
    { text: 'Î î', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'ж' },
    { text: 'ʒ' },
    { text: 'J j', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'к' },
    { text: 'k' },
    { text: 'K k', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'л' },
    { text: 'l' },
    { text: 'L l', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'м' },
    { text: 'm' },
    { text: 'M m', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'н' },
    { text: 'n' },
    { text: 'N n', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'о' },
    { text: 'o' },
    { text: 'O o', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'п' },
    { text: 'p' },
    { text: 'P p', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'к' },
    { text: 'q' },
    { text: 'Q q', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'р (вибрирующее)' },
    { text: 'r' },
    { text: 'R r', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'с' },
    { text: 's' },
    { text: 'S s', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'ш' },
    { text: 'ʃ' },
    { text: 'Ș ș', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'т' },
    { text: 't' },
    { text: 'T t', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'ц' },
    { text: 't͡s' },
    { text: 'Ț ț', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'у' },
    { text: 'u' },
    { text: 'U u', fontSize: 20 },
    { text: 'гласная' },
  ],
  [
    { text: 'в' },
    { text: 'v' },
    { text: 'V v', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'в' },
    { text: 'w' },
    { text: 'W w', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'кс' },
    { text: 'ks' },
    { text: 'X x', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'и' },
    { text: 'i' },
    { text: 'Y y', fontSize: 20 },
    { text: 'гласная, иногда согласная' },
  ],
  [
    { text: 'з' },
    { text: 'z' },
    { text: 'Z z', fontSize: 20 },
    { text: 'согласная' },
  ],
  [
    { text: 'к' },
    { text: 'k' },
    { text: 'CH ch', fontSize: 20 },
    { text: 'комбинация' },
  ],
  [
    { text: 'г' },
    { text: 'ɡ' },
    { text: 'GH gh', fontSize: 20 },
    { text: 'комбинация' },
  ],
];
